library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)
library(magrittr)
library(dplyr)
library(tidyr)
library(forcats)
library(purrr)
library(rlang)
library(stringr)
library(ggplot2)
library(bookdown)
library(knitr)
library(papaja)
library(magick)
library(here)
library(yaml)
library(afex)
library(janitor)
library(snakecase)
library(emmeans)
library(ggbeeswarm)
library(scales)
library(Hmisc)
library(broom)
library(effectsize)

# Custom packages
library(anecdotes1)
library(anecdotes2)

conflict_prefer("filter", "dplyr")
conflict_prefer("set_names", "rlang")
conflict_prefer("discard", "purrr")
