# Experiment 2 {#anecdotes-2}

```{r setup-anecdotes-2}
tar_load(descriptives_2)
tar_load(materials_2)
tar_load(results_2)
tar_load(plot_2)
```

The novel finding in Experiment 1 was that the anecdotal bias effect depends on
anecdote similarity. That is, participants allocated less capital to a project
when presented with an anecdote and conflicting statistics compared with when
they were presented with the statistics only. However, this effect was stronger
when the anecdote was similar to the current task compared with when it was less
similar. A negative anecdote only was used Experiment 1 because previous
research has found anecdotal bias for negative but not for positive anecdotes
[@jaramillo2019]. However, @jaramillo2019 investigated medical decision-making,
and the effect of anecdote valence, which may be different in a less salient
business context. In the study by @jaramillo2019, the positive anecdote involved
a treatment that led to a reduction in symptoms, while the negative anecdote
involved symptoms persisting. This framing may have led participants to perceive
the positive anecdote as a return to a reference point and the negative anecdote
as a continuation of a reduction in wellbeing relative to the reference point.
In business, however, both successful and failed business projects represent a
deviation from a reference point. To test this difference further, manipulation
of anecdote valence was added to Experiment 2.

To increase the experiment's power, anecdote valence and anecdote similarity
were manipulated within subjects. Further, Experiment 2 did not include the
anecdote & enhanced statistics condition because Experiment 1 found no
evidence for its effect. All participants saw the statistics only condition,
which did not contain an anecdote; therefore, this did not need to be
manipulated between subjects. Therefore, each participant was shown five
displays: one for the statistics only condition, and four for either the
anecdote only condition or the anecdote & statistics condition. These four
anecdote displays consisted of the similarity (low and high) $\times$ valence
(negative and positive) conditions.

In Experiment 1, assumptions about the pool from which the anecdote was sampled
were not clarified. In Experiment 2, participants were told that the anecdote
was sampled randomly and that it was not uniquely similar to the target project.
This was expected to lead to a reliance on statistical evidence, regardless of
the anecdote's similarity. However, people often struggle to use statistical
concepts presented descriptively, as seen in the enhanced statistics condition
in Experiment 1. Therefore, it was expected that the results of Experiment 1
would be replicated for the negative valence condition. Further, it was expected
that there would be a reverse effect in the positive valence condition.
Appendix \@ref(hypothesised-effects-anecdotes-2) shows a simulation of the
hypothesised effects.

The main effect of interest is the effect of anecdote similarity on anecdotal
bias. However, because in Experiment 2 all participants were presented with the
statistics only condition, a difference score was calculated to simplify the
analyses. Specifically, this was the difference between the allocation in the
anecdote & statistics conditions and the relevant allocation in the statistics
only condition. A score that is different from zero indicates deviation from the
allocation when only statistics were shown. The values in the anecdote
descriptions were different for the positive anecdotes than for the negative
anecdotes. However, the statistics only condition was the same for both.
Therefore, the difference scores for the positive anecdotes had to be
transformed further to directly compare the magnitude of the difference from the
statistics only condition between the positive and negative anecdote
(respectively). We did this by multiplying the positive anecdote difference
score by $-1$. This means that the bigger the difference score, the bigger the
anecdotal effect for both valence conditions. Therefore, Experiment 2 tested the
following hypotheses:

::: {.hypothesis #anecdote-similarity-2 name="anecdotal bias difference score" echo=TRUE}
The difference between budget allocations to the target project in the
statistics only condition and the anecdote & statistics condition will be higher
when the anecdote is similar to the target project compared with when it is
less similar.
:::

@jaramillo2019 found that the effect of a negative medical anecdote was stronger
compared with a positive one. However, business is dissimilar from medicine
because both gains and losses are more salient in medicine than business.
Therefore, Experiment 2 tested the following hypothesis:

::: {.hypothesis #anecdote-similarity-valence-interaction-2 name="anecdotal bias difference score valence interaction" echo=TRUE}
The effect of similarity on the anecdotal bias difference score will not depend
on anecdote valence.
:::

Similar to both @wainberg2013 and Hypothesis \@ref(hyp:statistics-anecdotes-1),
Experiment 1 found that participants do integrate statistics in their decisions
to some extent. This effect was expected to be replicated in Experiment 2.
Therefore, Experiment 2 tested the following hypothesis:

::: {.hypothesis #statistics-anecdotes-2 name="effect of statistics" echo=TRUE}
Budget allocations to the target project will be higher
for the high-similarity anecdote & statistics condition than for the
high-similarity anecdote only condition.
:::

::: {.hypothesis #statistics-valence-interaction-2 name="effect of statistics
valence interaction" echo=TRUE}
The effect of statistics will not depend on anecdote valence.
:::
