# Experiment 1 {#anecdotes-1}

```{r setup-anecdotes-1}
tar_load(descriptives_1)
tar_load(materials_1)
tar_load(results_1)
tar_load(plot_1)
```

Experiment 1 investigated the effects of anecdote similarity and bias on capital
allocation. Participants were assigned to the anecdote & statistics and
statistics only conditions as in @wainberg2018, with an addition of an anecdote
only condition. They were then asked to allocate a hypothetical budget between
two business projects. Participants were also presented with a case study that
was either similar or less similar to the target project, which Wainberg did not
do. Note, however, that a less similar project here is still significantly
related to the target project because they are both from the same industry.
Further, for the conditions in which statistical evidence was provided,
participants were presented with aggregated information about the success of
similar projects in the form of Net Present Value (NPV)[^npv] as well as a
reliability measure. NPV is the difference between the forecasted revenue of a
project and the initial investment in its development (accounting for the time
value of money), and was chosen here because it is the most common financial
measure that is used by executives in order to value business project proposals
[@graham2001; @remer1993; @graham2015]. One project was clearly better than the
other in terms of the statistical data, but the anecdotal evidence suggested the
opposite.

[^npv]:
    $$
    \text{NPV}=\sum_{t=0}^n \frac{R_t}{(1+i)^t},
    $$

    where $t$ is the time of the cash flow, $i$ is the discount rate, $R_t$ is the
    net cash flow, and $n$ is the total number of periods.

Previous research has found that people are persuaded more by negative anecdotes
than by positive statistical data in capital allocation scenarios
[@wainberg2018]. While studies have shown that similar anecdotes are more
persuasive than dissimilar anecdotes [@hoeken2009\; Study 3], it is unclear how
the anecdotal bias effect may depend on anecdote similarity. That is, it is
unclear whether people will respond to a simple negative association of the
anecdote to the target, or use a more sophisticated causal induction. The
present study is novel because we investigate both anecdotal bias and anecdotal
similarity. This is different from Hoeken and Hustinx because we presented
participants aggregated data to investigate anecdotal bias, whereas Hoeken and
Hustinx only presented anecdotes. Thus, the main question is whether anecdotal
bias will be greater when the anecdote is similar to the target project compared
with when it is less similar. The target project is supported by the statistics
but is inconsistent with the anecdotes. Further, Experiment 1 only uses negative
anecdotes. Therefore, the experiment would show evidence of anecdotal bias if
participants assigned to the statistics only condition allocated more money to
the target project compared with those in the anecdote & statistics condition.
Therefore, Experiment 1 tests the following hypothesis:

::: {.hypothesis #anecdote-similarity-anecdotes-1 name="anecdotal bias depends on the similarity of negative anecdotes" echo=TRUE}
Budget allocations to the target project will be higher when statistics only are
presented compared with when statistics are accompanied by an anecdote with high
similarity to the target project. In addition, budget allocations will not be
affected by anecdotes with low similarity. That is, the statistics only
condition will not differ from the low-similarity anecdote & statistics
condition.
:::

We predict that that the anecdotal bias effect will be partial. Specifically,
the participants presented with the high-similarity anecdote along with the
statistics would use some of the statistical information. Testing the high
similarity condition will provide an equivalent test to that of @wainberg2013.
Therefore, Experiment 1 tests the following:

::: {.hypothesis #statistics-anecdotes-1 name="effect of statistics for negative anecdotes" echo=TRUE}
Participants in the high-similarity anecdote & statistics condition (without the
enhanced statistics explanation) will allocate more capital to the target
project than those in the high-similarity anecdote only condition.
:::

In a condition we refer to as the anecdote & enhanced statistics condition,
participants were provided with additional information about the importance of
scientific thinking and statistical data. The statistics here are enhanced
because participants were provided with information that should help them better
interpret the statistics and therefore may be less affected by anecdotes.
Experiment 1 tests whether the effect of additional information on anecdotal
bias found in @wainberg2018 would be replicated in a capital allocation
scenario. Therefore, Experiment 1 tests the following hypothesis:

::: {.hypothesis #enhanced-statistics-anecdotes-1 name="effect of enhanced statistics for negative anecdotes" echo=TRUE}
Participants in the high-similarity anecdote & enhanced statistics condition
will allocate more capital to the target project than those in the
high-similarity anecdote & statistics condition.
:::
